#!/usr/bin/env bash

set -xeu

REPO="https://api.github.com/repos/microcai/gentoo-zh/contents/www-client/brave-bin"
EBUILD="$(curl "$REPO" \
  | jq -r ".[].name" \
  | grep -E "\.ebuild$" \
  | sort -V \
  | tail -1)"

if [[ -f "$EBUILD" ]]; then
  exit 0
fi

# Purge old versions:
rm -fv -- *.ebuild
rm -fv Manifest

# Fetch ebuild:
curl "$REPO/$EBUILD" \
  | jq -r ".content" \
  | base64 -d > "$EBUILD"

# Patch:
patch -b "$EBUILD" <<'EOF'
--- brave-bin-1.70.126.ebuild.old	2024-10-18 01:45:18.589769287 +0800
+++ brave-bin-1.70.126.ebuild	2024-10-18 01:58:04.348172578 +0800
@@ -109,8 +109,16 @@
 	    size=${logo##*_}
 		size=${size%.*}
 		newicon -s "${size}" "${logo}" ${PN/-bin}.png
 	done
 
 	pax-mark m "${BRAVE_HOME}/brave"
 	fperms 4711 "/${BRAVE_HOME}/chrome-sandbox"
+
+	# Replace the entrance with AUR version:
+	BRAVE_LINK="usr/bin/brave-browser-stable"
+	test -L "$BRAVE_LINK" || die
+	BRAVE_EXEC="$(realpath "$BRAVE_LINK")"
+	unlink "$BRAVE_LINK" || die
+	BRAVE_EXEC="${BRAVE_EXEC}" envsubst '${BRAVE_EXEC}' < "${FILESDIR}/brave-bin.sh" > "$BRAVE_LINK"
+	chmod +x "${BRAVE_LINK}" || die
 }
EOF

# Manifest:
sudo ebuild "$EBUILD" manifest
sudo chown "$(id -u):$(id -g)" Manifest
